// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD6uEPsdelS3_wonO-NC1gQK8vd3QTwHw',
    appId: '1:943315017128:web:2d0ef079f76425eaef519d',
    messagingSenderId: '943315017128',
    projectId: 'push-noti-56',
    authDomain: 'push-noti-56.firebaseapp.com',
    storageBucket: 'push-noti-56.appspot.com',
    measurementId: 'G-XQJS7698N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDbNdjpacBnt11jF4_CD_xKSbtj16M_eI',
    appId: '1:943315017128:android:f60e599ff5fcb7c8ef519d',
    messagingSenderId: '943315017128',
    projectId: 'push-noti-56',
    storageBucket: 'push-noti-56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmVqfUIegwsrKC7cY91i_rJ2g5fVeEhjg',
    appId: '1:943315017128:ios:bdc61c6be87895afef519d',
    messagingSenderId: '943315017128',
    projectId: 'push-noti-56',
    storageBucket: 'push-noti-56.appspot.com',
    iosBundleId: 'com.example.pushNotiMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmVqfUIegwsrKC7cY91i_rJ2g5fVeEhjg',
    appId: '1:943315017128:ios:df6285e7e417216def519d',
    messagingSenderId: '943315017128',
    projectId: 'push-noti-56',
    storageBucket: 'push-noti-56.appspot.com',
    iosBundleId: 'com.example.pushNotiMap.RunnerTests',
  );
}
